name: loan-approval-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - numpy>=1.20.0
    - pandas>=1.3.0
    - scikit-learn>=1.0.0
    - matplotlib>=3.4.0
    - seaborn>=0.11.0
    - mlflow>=2.19.0
    - PyYAML>=5.4.0
    - optuna>=2.10.0
    - joblib>=1.0.0